AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Template for the Dungeon Maestro lambda function. Processes commands from slack, and translates them into a DnD
    based request.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10

Parameters:
    Stage:
        Description: The stage for the function
        Type: String
        AllowedValues:
            - alpha
            - beta
            - gamma
            - prod
        Default: alpha
    EnableTracing:
        Description: Enable tracing in the service
        Type: String
        AllowedValues:
            - true
            - false
        Default: false

Conditions:
    ShouldEnableTracing: !Equals [true, !Ref EnableTracing]

Resources:
    DungeonMaestroFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./
            Handler: maestro
            Runtime: go1.x
            Tracing: !If [ShouldEnableTracing, Active, PassThrough]
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    Stage: !Ref Stage
                    Region: !Ref AWS::Region
            Events:
                DungeonMaestro:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: ANY

Outputs:

    DungeonMaestroApi:
      Description: "API Gateway endpoint URL for Prod stage for the Dungeon Maestro function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

    DungeonMaestroFunction:
      Description: "Dungeon Maestro Lambda Function ARN"
      Value: !GetAtt DungeonMaestroFunction.Arn

